baseurl: /westslope
permalink: pretty
future: true
markdown: kramdown
paginate: 5
repo: westslope
github_org: maptime
maptime:
  chapter: MaptimeWestSlope
  twitter: MaptimeWestCO
  facebook: wsosm
  #disqus: YOUR DISQUS USERNAME

gems:
  - jekyll-feed
